survos_translator:
  default_engine: libre_local
  engines:
    libre_local:
      type: libre
      base_uri: 'https://babel.survos.com'
      api_key: null
      # requires an API keu
#    libre_demo:
#      type: libre
#      base_uri: 'https://demo.libretranslate.com'
#      api_key: null
    deepl:
        type: deepl
        plan: free # sets  base_uri: 'https://api.deepl.com'
        api_key: '%env(resolve:DEEPL_API_KEY)%'
